name: Vynex NpmProtect Auto-Hunter
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Libs
        run: pip install httpx openai supabase python-dotenv
      - name: Execute
        env:
          # O segredo Ã© mapear os Secrets aqui:
          VT_API_KEY1: ${{ secrets.VT_API_KEY1 }}
          VT_API_KEY2: ${{ secrets.VT_API_KEY2 }}
          PROJECT_ID: "np-virustotal"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          MALWARE_BAZAAR_KEY: ${{ secrets.MALWARE_BAZAAR_KEY }}
          T_RIP_API_KEY: ${{ secrets.T_RIP_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: python main.py
